import streamlit as st
st.set_page_config(
    page_title="MCR-ALS",
    page_icon="⚛️",
    layout="wide",
    initial_sidebar_state="expanded"
)
header = st.container()
content = st.container()

with header:
    st.title(":purple[About MCR-ALS]")

with content:
    st.markdown('<div style="text-align: justify;">The Multivariate Curve Resolution (MCR, from English Multivariate Curve Resolution) is a family of methods with the objective of analyzing complex data, such as those generated by Nuclear Magnetic Resonance, and to solve the problem of mixture analysis in spectroscopy. As such, MCR has the ability to recover overlapping signals resulting from data obtained from an additive bilinear model of pure contributions from a single original data matrix (JUAN; JAUMOT; TAULER, 2014). </div>', unsafe_allow_html=True)
    st.markdown('<div style="text-align: justify;">By using the MCR method, it is possible to obtain a quantitative analysis of the different individual components present in the spectrum, such as determining their chemical concentrations. In addition, because it is an unsupervised technique, it does not require prior knowledge of the components, making it possible to analyze unknown or complex samples, thus allowing a more accurate and reliable interpretation of the data obtained.</div>', unsafe_allow_html=True)
    st.markdown('<div style="text-align: justify;">For the development of the algorithm, we used the pyMCR library (Python Multivariate Curve Resolution) which is a package for the resolution of multivariate curves and was projected to work with spectroscopic data, such as absorption spectroscopy, fluorescence, Raman, infrared, among others, but can also be applied in other areas of multivariate analysis.</div>', unsafe_allow_html=True)
